server:
  port: 8081
spring:
  application:
    name: ylep-estudiante-servicio

  datasource:
    url: jdbc:h2:mem:ylep_estudiante
    driver-class-name: org.h2.Driver
    username: howard
    password: yo
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
