server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/layder93122/microservicios.git
          searchPaths: config-data
          default-label: PRINCIPALCITO
  security:
    user:
      name: yohan
      password: pancca
